from . import gs_partner_division
from . import res_partner
from . import res_partner_category
from . import hr_department
from . import gs_product_family
from . import project_project
from . import project_task
from . import product_template
from . import crm_tag
from . import crm_lead
from . import call_scheduler_wizard
from . import gs_worker
from . import gs_worker_contract
from . import gs_worker_job_type
from . import gs_worker_job
from . import sale_order_line
from . import sale_order
from . import res_users
from . import gs_worker_transfer_wizard
